@startuml libsys

title E/R диаграмма для библиотечной системы
header Назаров Н.В., 2024

legend
    <b>Обозначения:</b>
    <u>атрибут</u> - ключ
endlegend

' Entities

entity Издательство {
    <u>имя</u>
    <u>адрес</u>
}

entity Книга {
    <u>ISBN</u>
    год
    название
    автор
    число страниц
}

entity Копия {
    <u>ISBN</u>
    <u>номер</u>
    полка
}

entity Категория {
    <u>имя</u>
}

entity Читатель {
    <u>номер</u>
    имя
    фамилия
    адрес
    день рождения
}

' Relationships

Издательство "1..N" -- "N" Книга : издало
Книга "N" -- "N" Категория : относится к категории
Читатель "0,1" -- "N" Копия : взял
Категория "N" -- "0,1" Категория : является подкатегорией

@enduml