services:

  psql-1:
    container_name: psql-1
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: db

  psql-2:
    container_name: psql-2
    image: postgres:alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: db