ALTER TABLE employees DISABLE TRIGGER ALL;
ALTER TABLE jobs DISABLE TRIGGER ALL;
ALTER TABLE job_history DISABLE TRIGGER ALL;

CALL add_job_hist(106, 'SY_ANAL');

SELECT * FROM job_history WHERE employee_id = 106;
SELECT * FROM employees WHERE employee_id = 106;

ALTER TABLE employees ENABLE TRIGGER ALL;
ALTER TABLE jobs ENABLE TRIGGER ALL;
ALTER TABLE job_history ENABLE TRIGGER ALL;